package com.example.icst.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.icst.Student;
import com.example.icst.Group;

import com.example.icst.dao.StudentDao;
import com.example.icst.dao.GroupDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig groupDaoConfig;

    private final StudentDao studentDao;
    private final GroupDao groupDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        groupDao = new GroupDao(groupDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(Group.class, groupDao);
    }
    
    public void clear() {
        studentDaoConfig.clearIdentityScope();
        groupDaoConfig.clearIdentityScope();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

}
